// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using neoDesk.Server.Data;

#nullable disable

namespace neoDesk.Server.Migrations
{
    [DbContext(typeof(NeoDeskDbContext))]
    [Migration("20251104171456_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("neoDesk.Server.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 11, 2, 18, 14, 56, 243, DateTimeKind.Local).AddTicks(6423),
                            CreatedByUserId = 1,
                            Description = "Drukarka nie drukuje dokumentów",
                            Status = 0,
                            Title = "Problem z drukarką"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToUserId = 3,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 11, 3, 18, 14, 56, 243, DateTimeKind.Local).AddTicks(6429),
                            CreatedByUserId = 2,
                            Description = "Aplikacja CRM wyświetla błąd przy logowaniu",
                            Status = 1,
                            Title = "Błąd w aplikacji"
                        });
                });

            modelBuilder.Entity("neoDesk.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 4, 18, 14, 56, 73, DateTimeKind.Local).AddTicks(7155),
                            Email = "admin@neodesk.com",
                            IsActive = true,
                            Name = "Administrator",
                            PasswordHash = "$2a$11$emn9V2E3Pun4VMLAqOgs6utz9.ac1q8Stk9/9.D8MQApAVqqIXxt6",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 4, 18, 14, 56, 158, DateTimeKind.Local).AddTicks(7088),
                            Email = "jan.kowalski@company.com",
                            IsActive = true,
                            Name = "Jan Kowalski",
                            PasswordHash = "$2a$11$Ru7U782nFpDx4Jcxxq/5J.ji1ZZYFjlFz49VRFg4l2djNEAIhTbvC",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 4, 18, 14, 56, 243, DateTimeKind.Local).AddTicks(6109),
                            Email = "anna.nowak@company.com",
                            IsActive = true,
                            Name = "Anna Nowak",
                            PasswordHash = "$2a$11$4tgJletrFZ46xY.7Nvnf1eDlA0JX.3EUkJNQzU5CfNLL5nPvyfgcq",
                            Role = 1
                        });
                });

            modelBuilder.Entity("neoDesk.Server.Models.Ticket", b =>
                {
                    b.HasOne("neoDesk.Server.Models.User", "AssignedToUser")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("neoDesk.Server.Models.User", "CreatedByUser")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("neoDesk.Server.Models.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("CreatedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
