// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using neoDesk.Server.Data;

#nullable disable

namespace neoDesk.Server.Migrations
{
    [DbContext(typeof(NeoDeskDbContext))]
    [Migration("20260201182522_LastUpdatedAt added")]
    partial class LastUpdatedAtadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("neoDesk.Server.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("neoDesk.Server.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 19, 25, 21, 950, DateTimeKind.Local).AddTicks(6592),
                            CreatedByUserId = 1,
                            Description = "Drukarka nie drukuje dokumentów",
                            LastUpdatedAt = new DateTime(2026, 1, 30, 19, 25, 21, 950, DateTimeKind.Local).AddTicks(6595),
                            Status = 0,
                            Title = "Problem z drukarką"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToUserId = 3,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 1, 31, 19, 25, 21, 950, DateTimeKind.Local).AddTicks(6604),
                            CreatedByUserId = 2,
                            Description = "Aplikacja CRM wyświetla błąd przy logowaniu",
                            LastUpdatedAt = new DateTime(2026, 1, 31, 19, 25, 21, 950, DateTimeKind.Local).AddTicks(6605),
                            Status = 1,
                            Title = "Błąd w aplikacji"
                        });
                });

            modelBuilder.Entity("neoDesk.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 19, 25, 21, 779, DateTimeKind.Local).AddTicks(9017),
                            Email = "admin@neodesk.com",
                            IsActive = true,
                            Name = "Administrator",
                            PasswordHash = "$2a$11$.kuw3yiGvBZScszOmwrvGOaPedf32.TcIrYQXkEEjqD7vfQmAEHOS",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 1, 19, 25, 21, 865, DateTimeKind.Local).AddTicks(4845),
                            Email = "jan.kowalski@company.com",
                            IsActive = true,
                            Name = "Jan Kowalski",
                            PasswordHash = "$2a$11$PDAj/1A1ZSCR9bXAlz3cyu.IHmQcjueG2p1vCwLrNzj8x8OBTdPTG",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 1, 19, 25, 21, 950, DateTimeKind.Local).AddTicks(6214),
                            Email = "anna.nowak@company.com",
                            IsActive = true,
                            Name = "Anna Nowak",
                            PasswordHash = "$2a$11$j5FxqvKDvlR1OcdqqMu3NeIze51HlA1NktRtvLhiQVCl88/c8xfTu",
                            Role = 1
                        });
                });

            modelBuilder.Entity("neoDesk.Server.Models.Comment", b =>
                {
                    b.HasOne("neoDesk.Server.Models.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("neoDesk.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("neoDesk.Server.Models.Ticket", b =>
                {
                    b.HasOne("neoDesk.Server.Models.User", "AssignedToUser")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("neoDesk.Server.Models.User", "CreatedByUser")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("neoDesk.Server.Models.Ticket", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("neoDesk.Server.Models.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("CreatedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
