// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using neoDesk.Server.Data;

#nullable disable

namespace neoDesk.Server.Migrations
{
    [DbContext(typeof(NeoDeskDbContext))]
    [Migration("20260130181552_TicketId added to Comment")]
    partial class TicketIdaddedtoComment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("neoDesk.Server.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("neoDesk.Server.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 1, 28, 19, 15, 52, 412, DateTimeKind.Local).AddTicks(2403),
                            CreatedByUserId = 1,
                            Description = "Drukarka nie drukuje dokumentów",
                            Status = 0,
                            Title = "Problem z drukarką"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToUserId = 3,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 1, 29, 19, 15, 52, 412, DateTimeKind.Local).AddTicks(2409),
                            CreatedByUserId = 2,
                            Description = "Aplikacja CRM wyświetla błąd przy logowaniu",
                            Status = 1,
                            Title = "Błąd w aplikacji"
                        });
                });

            modelBuilder.Entity("neoDesk.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 19, 15, 52, 241, DateTimeKind.Local).AddTicks(6325),
                            Email = "admin@neodesk.com",
                            IsActive = true,
                            Name = "Administrator",
                            PasswordHash = "$2a$11$p8HLJoYZpplkoFyKbTywEOqCDG3SL2JZeHXgi6g9mYZgrPCcQ8U2S",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 30, 19, 15, 52, 326, DateTimeKind.Local).AddTicks(9040),
                            Email = "jan.kowalski@company.com",
                            IsActive = true,
                            Name = "Jan Kowalski",
                            PasswordHash = "$2a$11$JPsSXGDbGydIlqoMf5YJBuOA8vQv3sXOFEPDRnq/Ndp7X36SXFoFa",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 30, 19, 15, 52, 412, DateTimeKind.Local).AddTicks(2090),
                            Email = "anna.nowak@company.com",
                            IsActive = true,
                            Name = "Anna Nowak",
                            PasswordHash = "$2a$11$z6dPgpX0JRvuO3TBeokw0uz3zPEs8VprJkDrn1BcNgXHIyiX8dI/S",
                            Role = 1
                        });
                });

            modelBuilder.Entity("neoDesk.Server.Models.Ticket", b =>
                {
                    b.HasOne("neoDesk.Server.Models.User", "AssignedToUser")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("neoDesk.Server.Models.User", "CreatedByUser")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("neoDesk.Server.Models.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("CreatedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
